/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author alfre
 */
public class MenuPaciente extends javax.swing.JFrame {

    /**
     * Creates new form MenuPaciente
     */
    public MenuPaciente() {
        initComponents();
        cargarNombreUsuario();
    }

    private void cargarNombreUsuario() {
        String nombreUsuario = "Nombre del usuario";
        jTextField3.setText(nombreUsuario);
    }                                 

    private void btnEliminarCitaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        EliminarCita ventanaEliminarCita = new EliminarCita();
        ventanaEliminarCita.setVisible(true);
        this.setVisible(false); 
    }                                               

    private void btnCitaEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        CitaEmergencia ventanaCitaEmergencia = new CitaEmergencia();
        ventanaCitaEmergencia.setVisible(true);
        this.setVisible(false);
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConfirmar4 = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnHistorialConsultas = new javax.swing.JButton();
        btnMisCitas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgendarCita = new javax.swing.JButton();
        btnEliminarCita = new javax.swing.JButton();
        btnCitaEmergencia = new javax.swing.JButton();

        btnConfirmar4.setBackground(new java.awt.Color(255, 0, 51));
        btnConfirmar4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConfirmar4.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar4.setText("Cerrar Sesion");
        btnConfirmar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmar4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPerfil.setBackground(new java.awt.Color(255, 0, 51));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnHistorialConsultas.setBackground(new java.awt.Color(255, 0, 51));
        btnHistorialConsultas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHistorialConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialConsultas.setText("Historial de consultas");
        btnHistorialConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialConsultasActionPerformed(evt);
            }
        });

        btnMisCitas.setBackground(new java.awt.Color(255, 0, 51));
        btnMisCitas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMisCitas.setForeground(new java.awt.Color(255, 255, 255));
        btnMisCitas.setText("Mis citas");
        btnMisCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisCitasActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 51));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Clinica BD");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Usuario:");

        btnAgendarCita.setBackground(new java.awt.Color(255, 0, 0));
        btnAgendarCita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgendarCita.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendarCita.setText("Agendar cita");
        btnAgendarCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarCitaActionPerformed(evt);
            }
        });

        btnEliminarCita.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarCita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEliminarCita.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarCita.setText("Eliminar cita");

        btnCitaEmergencia.setBackground(new java.awt.Color(255, 0, 0));
        btnCitaEmergencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCitaEmergencia.setForeground(new java.awt.Color(255, 255, 255));
        btnCitaEmergencia.setText("Cita de emergencia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnCerrarSesion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCitaEmergencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEliminarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMisCitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHistorialConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAgendarCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(393, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnPerfil)))
                .addGap(18, 18, 18)
                .addComponent(btnMisCitas)
                .addGap(18, 18, 18)
                .addComponent(btnHistorialConsultas)
                .addGap(18, 18, 18)
                .addComponent(btnAgendarCita)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarCita)
                .addGap(18, 18, 18)
                .addComponent(btnCitaEmergencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        PerfilPaciente ventanaPerfil = new PerfilPaciente();
        ventanaPerfil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnHistorialConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialConsultasActionPerformed
        HistorialConsultasPaciente ventanaHistorial = new HistorialConsultasPaciente();
        ventanaHistorial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHistorialConsultasActionPerformed

    private void btnMisCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisCitasActionPerformed
        CitasPaciente ventanaMisCitas = new CitasPaciente();
        ventanaMisCitas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMisCitasActionPerformed

    private void btnConfirmar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfirmar4ActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        IniciarSesion ventanaIniciarSesion = new IniciarSesion();
        ventanaIniciarSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        cargarNombreUsuario();
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void btnAgendarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarCitaActionPerformed
        AgendarCita ventanaAgendarCita = new AgendarCita();
        ventanaAgendarCita.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAgendarCitaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarCita;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCitaEmergencia;
    private javax.swing.JButton btnConfirmar4;
    private javax.swing.JButton btnEliminarCita;
    private javax.swing.JButton btnHistorialConsultas;
    private javax.swing.JButton btnMisCitas;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
