/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BO.UsuarioBO;
import conexion.Conexion;
import excepciones.NegocioException;

/**
 *
 * @author Abraham Coronel Bringas
 */
public class MenuMedico extends javax.swing.JFrame {

    private UsuarioBO usuarioBO;
    private int idUsuario;

    public MenuMedico(UsuarioBO usuarioBO, int idUsuario) {
        this.usuarioBO = usuarioBO;
        this.idUsuario = idUsuario;
        initComponents();
        cargarNombreUsuario();
    }

    public MenuMedico() {
        this.usuarioBO = new UsuarioBO(new Conexion()); // Asegúrate de que 'Conexion' implemente 'IConexion'
        this.idUsuario = 1; // O cualquier ID de usuario predeterminado
        initComponents();
        cargarNombreUsuario();
    }
    

    private void cargarNombreUsuario() {
        try {
            String nombreUsuario = usuarioBO.obtenerNombreUsuario(idUsuario);
            jTextField1.setText(nombreUsuario);
        } catch (NegocioException e) {
            jTextField1.setText("Error al cargar nombre");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActualizarEstado = new javax.swing.JButton();
        btnMiPerfil = new javax.swing.JButton();
        btnConsultarAgenda = new javax.swing.JButton();
        btnHistorialDeConsultas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnActualizarEstado.setBackground(new java.awt.Color(255, 0, 51));
        btnActualizarEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActualizarEstado.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarEstado.setText("Actualizar Estado");
        btnActualizarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEstadoActionPerformed(evt);
            }
        });

        btnMiPerfil.setBackground(new java.awt.Color(255, 0, 51));
        btnMiPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMiPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnMiPerfil.setText("Mi perfil");
        btnMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiPerfilActionPerformed(evt);
            }
        });

        btnConsultarAgenda.setBackground(new java.awt.Color(255, 0, 51));
        btnConsultarAgenda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnConsultarAgenda.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultarAgenda.setText("Consultar agenda");
        btnConsultarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarAgendaActionPerformed(evt);
            }
        });

        btnHistorialDeConsultas.setBackground(new java.awt.Color(255, 0, 51));
        btnHistorialDeConsultas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHistorialDeConsultas.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorialDeConsultas.setText("Historial de consultas");
        btnHistorialDeConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialDeConsultasActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(255, 0, 51));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Clinica BD");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Usuario:");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(720, 720, 720))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnHistorialDeConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultarAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnActualizarEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMiPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(btnMiPerfil)
                .addGap(18, 18, 18)
                .addComponent(btnActualizarEstado)
                .addGap(18, 18, 18)
                .addComponent(btnHistorialDeConsultas)
                .addGap(18, 18, 18)
                .addComponent(btnConsultarAgenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEstadoActionPerformed
        int idMedico = 5;   
        EstadoMedico ventanaActualizarEstado = new EstadoMedico(idMedico);
        ventanaActualizarEstado.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActualizarEstadoActionPerformed

    private void btnMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiPerfilActionPerformed
        PerfilMedico ventanaMiPerfil = new PerfilMedico();
        ventanaMiPerfil.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMiPerfilActionPerformed

    private void btnConsultarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarAgendaActionPerformed
        AgendaMedico ventanaConsultarAgenda = new AgendaMedico();
        ventanaConsultarAgenda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultarAgendaActionPerformed

    private void btnHistorialDeConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialDeConsultasActionPerformed
        ConsultasMedico ventanaHistorial = new ConsultasMedico();
        ventanaHistorial.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHistorialDeConsultasActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        IniciarSesion ventanaIniciarSesion = new IniciarSesion();
        ventanaIniciarSesion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEstado;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnConsultarAgenda;
    private javax.swing.JButton btnHistorialDeConsultas;
    private javax.swing.JButton btnMiPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
